"use strict";

const fs = require("fs/promises");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const gitDir = path.join(repoRoot, ".git");
const hooksDir = path.join(gitDir, "hooks");
const preCommitPath = path.join(hooksDir, "pre-commit");

const hookScript = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.js.
# Runs the test suite before allowing commits.

npm test
status=$?
if [ $status -ne 0 ]; then
  echo ""
  echo "pre-commit: npm test failed. Commit aborted."
  exit $status
fi
`;

async function main() {
  try {
    await fs.access(gitDir);
  } catch {
    console.log("setup-hooks: .git directory not found. Skipping hook installation.");
    return;
  }

  await fs.mkdir(hooksDir, { recursive: true });

  let existing = "";
  try {
    existing = await fs.readFile(preCommitPath, "utf8");
  } catch {
    existing = "";
  }

  if (existing === hookScript) {
    console.log("setup-hooks: pre-commit hook already up to date.");
    return;
  }

  await fs.writeFile(preCommitPath, hookScript, "utf8");

  try {
    await fs.chmod(preCommitPath, 0o755);
  } catch {
    // chmod can fail on some Windows filesystems; hook still works for Git Bash.
  }

  console.log("setup-hooks: installed .git/hooks/pre-commit to run npm test.");
}

main().catch((error) => {
  console.error("setup-hooks: failed:", error);
  process.exit(1);
});
